// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ5nQJj7re84he93bDxmMAoyxH32ldi5U',
    appId: '1:768778503722:web:1e598c24f8d996e4086553',
    messagingSenderId: '768778503722',
    projectId: 'classcue-77029',
    authDomain: 'classcue-77029.firebaseapp.com',
    storageBucket: 'classcue-77029.firebasestorage.app',
    measurementId: 'G-QFDJTXSVLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-zU8Cet991IBLC6s4sHuyrqk4H24v_c',
    appId: '1:768778503722:android:e64c94927856e749086553',
    messagingSenderId: '768778503722',
    projectId: 'classcue-77029',
    storageBucket: 'classcue-77029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMHBiVKfXJOBYQi02UoffktRFWtKLdyE',
    appId: '1:768778503722:ios:00be01607b2d5534086553',
    messagingSenderId: '768778503722',
    projectId: 'classcue-77029',
    storageBucket: 'classcue-77029.firebasestorage.app',
    iosBundleId: 'com.classcue.app.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlMHBiVKfXJOBYQi02UoffktRFWtKLdyE',
    appId: '1:768778503722:ios:00be01607b2d5534086553',
    messagingSenderId: '768778503722',
    projectId: 'classcue-77029',
    storageBucket: 'classcue-77029.firebasestorage.app',
    iosBundleId: 'com.classcue.app.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ5nQJj7re84he93bDxmMAoyxH32ldi5U',
    appId: '1:768778503722:web:aa16125a86d5a59e086553',
    messagingSenderId: '768778503722',
    projectId: 'classcue-77029',
    authDomain: 'classcue-77029.firebaseapp.com',
    storageBucket: 'classcue-77029.firebasestorage.app',
    measurementId: 'G-J2B5PWVH3R',
  );
}
